name: 'Graeme Taylor Photography '
favicon: null
layout_spectrum: 0.75359
typography_spectrum: 0.24931
title: Blue Mountains Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#38453e'
    - '#71706e'
    - '#c6c6ce'
    - '#de9058'
  brandStrength: 0.5
  lightness: 0.23655
  saturation: 0.875
  rhythmicContrast: 0.75
purpose:
  - name: null
    item: null
    url: null
