name: 'Graeme Taylor Photography '
favicon: null
layout_spectrum: 0.99719
typography_spectrum: 0.000845
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefc'
    - '#020106'
    - '#ffc198'
    - '#653463'
    - '#9a9fd9'
  brandStrength: 0.5
  lightness: 0.23655
  saturation: 0.5625
  rhythmicContrast: 0.472128
purpose:
  - name: null
    item: null
    url: null
