analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#020202'
    - '#dadada'
    - '#525252'
    - '#a5a5a5'
  brandStrength: 0.5
  lightness: 0.23655
  rhythmicContrast: 0.472128
  saturation: 0.5625
cta: {}
layout_spectrum: 0
name: 'Graeme Taylor Photography '
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.78125
