analytics: {}
color:
  brandColors:
    - '#B8B8B8'
    - '#000000'
    - '#888888'
    - '#000000'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.23655
  rhythmicContrast: 0.472128
  saturation: 0.5625
cta: {}
layout_spectrum: 0
name: 'Graeme Taylor Photography '
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.78125
