name: 'Graeme Taylor Photography '
favicon: null
layout_spectrum: 0.011824
typography_spectrum: 0.000845
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B8B8'
    - '#000000'
    - '#888888'
    - '#000000'
    - '#000000'
  brandStrength: 0.374155
  lightness: 0.23655
  saturation: 0.300247
  rhythmicContrast: 0.472128
purpose:
  - name: null
    item: null
    url: null
